export const WordsAd = [
    {
        id:1,
        image:"/assets/appImages/brainGame.png",
        link:"https://play.google.com/store/apps/details?id=com.tHN.game.android",
    },
    {
        id:2,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:3,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:4,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:5,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:6,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:7,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:8,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:9,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:10,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:11,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:12,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:13,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:14,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
    {
        id:15,
        image:"/assets/appImages/hhCrew.png",
        link:"https://play.google.com/store/apps/details?id=com.hidehouse.game",
    },
];